### ISSUE TITLE
Error RequestError [HttpError]: Not Found

### ISSUE THREAD

**Issue by reidwil-jb** [maxkomarychev/octions#13]
When using the `maxkomarychev/octions/octions/issues/create-comment@master` action in my workflow, I am seeing failures. 
From what I can tell, when the comment is trying to post, the url is malformed and is missing the ID at the end of the url string.

**Note**: I am using [khan/pull-request-comment-trigger@master](https://github.com/Khan/pull-request-comment-trigger) to trigger a linting step that writes the its logs to `output.txt` which is the body of the `create-comment` step

Error output:
```
error RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/maxkomarychev/octions/master/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async octionRequest (/home/runner/work/_actions/maxkomarychev/octions/master/src/utils/request.js:25:18) {
  name: 'HttpError',
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 22 Jul 2021 21:33:01 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '07C1:8A5D:1443CB1:2892FD6:60F9E40D',
    'x-ratelimit-limit': '15000',
    'x-ratelimit-remaining': '14998',
    'x-ratelimit-reset': '1626993180',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '2',
    'x-xss-protection': '0'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/my_org/my_repo/issues//comments',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-request.js/5.4.2 Node.js/12.13.1 (Linux 5.8; x64)',
      authorization: '***',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"body":"```\\n-------------\\nDiff Quality\\nQuality Report: sqlfluff\\nDiff: remotes/origin/develop...HEAD, staged and unstaged changes\\n-------------\\nNo lines with quality information in this diff.\\n-------------\\n```\\n"}'
  },
  documentation_url: 'https://docs.github.com/rest'
}
```

**Comment by reidwil-jb** [comment]
I was not using this with the trigger:
```yaml
on:
  issue_comment:
    types: [created]
```
